@Api_HostAddress = https://localhost:7147

GET {{Api_HostAddress}}/users/
Accept: application/json

###

POST {{Api_HostAddress}}/users/
Content-Type: application/json

{
    "id": "{{$random.uuid}}",
    "category": "premium",
    "amount": 0.2,
    "createdAt": "{{$isoTimestamp}}"
}